# -*- coding: utf-8 -*-
"""OneClickFastAPI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p7AuBxa12tLwKe1mpn127WeT50cnz__N

# Abre la API con un enlace público
"""

!pip install fastapi uvicorn pyngrok nest_asyncio
from fastapi import FastAPI
import uvicorn
from pyngrok import ngrok
import nest_asyncio

app = FastAPI()

@app.get("/")
def index():
    return {"Esto es una": "prueba!"}


# Aplica nest_asyncio para permitir la ejecución de bucles de eventos anidados
nest_asyncio.apply()

# Configura tu token de autenticación de ngrok (si tienes uno)
# ngrok.set_auth_token("token")

# Crea un túnel seguro desde un servidor en la nube hasta el puerto 8000
public_url = ngrok.connect(8000)
print(f"Public URL: {public_url}")

uvicorn.run(app, host="0.0.0.0", port=8000)